import { useState } from 'react';
import { DocumentDuplicateIcon, ClipboardDocumentCheckIcon, PrinterIcon } from '@heroicons/react/24/outline';

const DOC_TYPES = [
  { id: 'nda', label: 'Non-Disclosure Agreement (NDA)', icon: '🔒' },
  { id: 'ip_assignment', label: 'IP Assignment Agreement', icon: '📋' },
  { id: 'co_inventor', label: 'Co-Inventor Declaration', icon: '🤝' },
];

const DURATIONS = ['1 year', '2 years', '3 years', '5 years', 'Indefinitely'];

const generateNDA = (form) => {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `NON-DISCLOSURE AGREEMENT

This Non-Disclosure Agreement ("Agreement") is entered into as of ${today}
("Effective Date") by and between:

DISCLOSING PARTY:
  ${form.disclosing}
  ("Disclosing Party")

RECEIVING PARTY:
  ${form.receiving}
  ("Receiving Party")

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ARTICLE 1 — PURPOSE

The Disclosing Party intends to disclose certain confidential information relating to:

  "${form.project}"

to the Receiving Party for the purpose of evaluating or assisting with the above-described project or collaboration (the "Purpose").

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ARTICLE 2 — DEFINITION OF CONFIDENTIAL INFORMATION

"Confidential Information" means any data or information disclosed by the Disclosing Party to the Receiving Party, whether orally or in writing, that is designated as confidential or that reasonably should be understood to be confidential, including but not limited to:

  (a) Technical data, trade secrets, know-how, research;
  (b) Product plans, designs, drawings, engineering, and source code;
  (c) Marketing strategies, business plans, financial projections;
  (d) Any information related to the project described in Article 1.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ARTICLE 3 — OBLIGATIONS OF RECEIVING PARTY

The Receiving Party agrees to:

  (a) Hold all Confidential Information in strict confidence;
  (b) Not disclose, transfer, or release the Confidential Information to any third party without prior written consent of the Disclosing Party;
  (c) Use the Confidential Information solely for the Purpose defined herein;
  (d) Protect the Confidential Information with at least the same degree of care used to protect its own confidential information, but in no event less than reasonable care;
  (e) Promptly notify the Disclosing Party upon discovery of any unauthorized use or disclosure of Confidential Information.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ARTICLE 4 — EXCLUSIONS

The obligations of confidentiality shall not apply to information that:

  (a) Is or becomes publicly known through no breach of this Agreement;
  (b) Was rightfully in the Receiving Party's possession prior to disclosure;
  (c) Is independently developed by the Receiving Party without use of Confidential Information;
  (d) Is required to be disclosed by applicable law or court order.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ARTICLE 5 — TERM

This Agreement shall remain in effect for a period of ${form.duration} from the Effective Date, unless terminated earlier by mutual written consent.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ARTICLE 6 — NO LICENSE

Nothing in this Agreement grants the Receiving Party any intellectual property rights, licenses, or ownership in the Confidential Information or any related patents, copyrights, or trademarks.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ARTICLE 7 — GOVERNING LAW & REMEDIES

This Agreement shall be governed by the laws of India / the applicable jurisdiction. The Disclosing Party shall be entitled to seek injunctive or other equitable relief in addition to any other remedies available at law.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIGNATURES

AGREED AND ACCEPTED by the parties hereto:

DISCLOSING PARTY:

  Name: ${form.disclosing}
  Signature: _______________________________
  Date: ___________________________________


RECEIVING PARTY:

  Name: ${form.receiving}
  Signature: _______________________________
  Date: ___________________________________

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISCLAIMER: This is a template document for educational purposes only. It does NOT constitute legal advice. Have this agreement reviewed by a qualified attorney before use.

Generated by IPR Awareness Portal | ${new Date().toUTCString()}`;
};

const generateIPAssignment = (form) => {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `INTELLECTUAL PROPERTY ASSIGNMENT AGREEMENT

This IP Assignment Agreement ("Agreement") is made as of ${today}
("Effective Date") between:

ASSIGNOR (Inventor):
  ${form.disclosing}

ASSIGNEE (Receiving Party / Organization):
  ${form.receiving}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

1. SUBJECT MATTER

The Assignor hereby irrevocably assigns, transfers, and conveys to the Assignee all right, title, and interest in and to the following intellectual property (the "IP"):

  Project / Work: "${form.project}"

  Including all associated patents, patent applications, copyrights, trade secrets, know-how, inventions, trademarks, and any other intellectual property rights worldwide arising from or relating to the above work.

2. REPRESENTATIONS AND WARRANTIES

The Assignor represents and warrants that:
  (a) The Assignor is the sole and original creator/inventor of the IP;
  (b) The Assignor has full right and authority to assign the IP;
  (c) The IP does not infringe upon any third-party intellectual property rights;
  (d) There are no pending claims or encumbrances against the IP.

3. CONSIDERATION

In consideration for this assignment, the Assignee agrees to [describe consideration — e.g., compensation, equity, credit, etc.]. Both parties agree that this consideration is adequate and sufficient.

4. FURTHER ASSURANCE

The Assignor agrees to execute any additional documents and take any actions reasonably requested by the Assignee to perfect, confirm, or record the assignment worldwide, including patent filings and copyright registrations.

5. TERM

This agreement is perpetual and irrevocable unless both parties agree in writing to modify or terminate it.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIGNATURES

ASSIGNOR:

  Name: ${form.disclosing}
  Signature: _______________________________
  Date: ___________________________________

ASSIGNEE:

  Name: ${form.receiving}
  Signature: _______________________________
  Date: ___________________________________

WITNESS (optional):

  Name: _______________________________
  Signature: _______________________________
  Date: ___________________________________

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by IPR Awareness Portal | ${new Date().toUTCString()}`;
};

const generateCoInventor = (form) => {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  return `CO-INVENTOR DECLARATION

Date: ${today}

RE: Invention — "${form.project}"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

We, the undersigned, hereby jointly declare that:

1. We are the original and only inventors of the above-named invention.

2. We believe the above-named invention is novel and has not been previously disclosed, published, or patented in the same form.

3. Our respective contributions to the invention are as follows:

   Inventor 1 — ${form.disclosing}:
   Contribution: [Describe technical contribution here]

   Inventor 2 — ${form.receiving}:
   Contribution: [Describe technical contribution here]

4. We acknowledge our duty to disclose to the relevant patent office all information known to us to be material to the patentability of this invention.

5. We have reviewed the contents of any patent application prepared for this invention and confirm it is complete and accurate.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SIGNATURES

Inventor 1:

  Name: ${form.disclosing}
  Signature: _______________________________
  Date: ___________________________________

Inventor 2:

  Name: ${form.receiving}
  Signature: _______________________________
  Date: ___________________________________

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by IPR Awareness Portal | ${new Date().toUTCString()}`;
};

const NDAGenerator = () => {
  const [form, setForm] = useState({ disclosing: '', receiving: '', project: '', type: 'nda', duration: '2 years' });
  const [doc, setDoc] = useState('');
  const [copied, setCopied] = useState(false);

  const handleChange = (e) => setForm(f => ({ ...f, [e.target.name]: e.target.value }));

  const isValid = form.disclosing && form.receiving && form.project && form.type;

  const handleGenerate = () => {
    if (!isValid) return;
    if (form.type === 'nda') setDoc(generateNDA(form));
    else if (form.type === 'ip_assignment') setDoc(generateIPAssignment(form));
    else setDoc(generateCoInventor(form));
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(doc);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 animate-fade-in">
      {/* Header */}
      <div className="text-center mb-10">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-500 to-secondary-500 flex items-center justify-center mx-auto mb-4 shadow-[0_0_30px_rgba(255,183,0,0.3)]">
          <DocumentDuplicateIcon className="h-9 w-9 text-white" />
        </div>
        <h1 className="page-title">Legal Document Generator</h1>
        <p className="text-slate-400 max-w-xl mx-auto">
          Generate NDA, IP Assignment Agreements, and Co-Inventor Declarations with your details pre-filled — ready to print and sign.
        </p>
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Form */}
        <div className="glass-card p-6 space-y-5">
          <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider border-b border-white/5 pb-3">Document Details</h2>

          {/* Document Type */}
          <div>
            <label className="label">Document Type *</label>
            <div className="space-y-2">
              {DOC_TYPES.map(dt => (
                <label key={dt.id} className={`flex items-center gap-3 p-3 rounded-xl border cursor-pointer transition-all ${
                  form.type === dt.id
                    ? 'border-primary-500/40 bg-primary-500/10'
                    : 'border-white/5 bg-white/[0.02] hover:border-white/10'
                }`}>
                  <input type="radio" name="type" value={dt.id} checked={form.type === dt.id} onChange={handleChange} className="sr-only" />
                  <span className="text-xl">{dt.icon}</span>
                  <span className="text-sm font-medium text-white">{dt.label}</span>
                </label>
              ))}
            </div>
          </div>

          <div>
            <label className="label">
              {form.type === 'co_inventor' ? 'Inventor 1 (You)' : 'Disclosing Party'} *
            </label>
            <input name="disclosing" value={form.disclosing} onChange={handleChange} className="input"
              placeholder={form.type === 'ip_assignment' ? 'Inventor full name' : 'Your name or organization'} />
          </div>

          <div>
            <label className="label">
              {form.type === 'co_inventor' ? 'Inventor 2 (Co-inventor)' : form.type === 'ip_assignment' ? 'Assignee (Organization)' : 'Receiving Party'} *
            </label>
            <input name="receiving" value={form.receiving} onChange={handleChange} className="input"
              placeholder={form.type === 'ip_assignment' ? 'Organization or company receiving IP' : 'Collaborator or entity name'} />
          </div>

          <div>
            <label className="label">Project / Confidential Information *</label>
            <textarea name="project" value={form.project} onChange={handleChange}
              className="input min-h-[80px] resize-none"
              placeholder="Briefly describe the project or confidential information…" />
          </div>

          {form.type === 'nda' && (
            <div>
              <label className="label">Duration of Confidentiality</label>
              <select name="duration" value={form.duration} onChange={handleChange} className="input">
                {DURATIONS.map(d => <option key={d} value={d}>{d}</option>)}
              </select>
            </div>
          )}

          <button onClick={handleGenerate} disabled={!isValid} className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50">
            <DocumentDuplicateIcon className="h-5 w-5" />
            Generate Document
          </button>
        </div>

        {/* Document Output */}
        <div>
          {doc ? (
            <div className="space-y-4">
              <div className="glass-card border border-primary-500/20 p-4 relative">
                <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-primary-500 to-secondary-500 rounded-t-2xl" />
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-semibold text-primary-300 flex items-center gap-2">
                    <DocumentDuplicateIcon className="h-4 w-4" />
                    {DOC_TYPES.find(d => d.id === form.type)?.label}
                  </h3>
                  <span className="text-xs text-slate-600 font-mono">DRAFT • REVIEW REQUIRED</span>
                </div>
                <pre className="text-xs text-slate-300 whitespace-pre-wrap font-mono leading-relaxed max-h-[580px] overflow-y-auto bg-black/30 rounded-lg p-4 border border-white/5">
                  {doc}
                </pre>
              </div>
              <div className="flex gap-3">
                <button onClick={handleCopy} className="btn-secondary flex-1 flex items-center justify-center gap-2 text-sm">
                  <ClipboardDocumentCheckIcon className="h-4 w-4" />
                  {copied ? '✅ Copied!' : 'Copy Text'}
                </button>
                <button onClick={() => window.print()} className="btn-primary flex-1 flex items-center justify-center gap-2 text-sm">
                  <PrinterIcon className="h-4 w-4" />
                  Print / Save PDF
                </button>
              </div>
              <p className="text-xs text-slate-600 text-center">⚠️ This is a template draft. Have it reviewed by a qualified attorney before signing.</p>
            </div>
          ) : (
            <div className="glass-card border border-dashed border-white/10 p-10 text-center h-full flex flex-col items-center justify-center gap-4">
              <DocumentDuplicateIcon className="h-12 w-12 text-slate-700" />
              <p className="text-slate-500 text-sm">Your legal document will appear here once you fill in the details and click Generate.</p>
              <div className="text-xs text-slate-600 space-y-1">
                <p>✦ NDA Templates</p>
                <p>✦ IP Assignment Agreements</p>
                <p>✦ Co-Inventor Declarations</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default NDAGenerator;
