import { useState } from 'react';
import { DocumentTextIcon, PlusIcon, TrashIcon, ClipboardDocumentCheckIcon, PrinterIcon } from '@heroicons/react/24/outline';

const FIELDS = [
  { id: 'software', label: 'Software & Computing' },
  { id: 'mechanical', label: 'Mechanical Engineering' },
  { id: 'electrical', label: 'Electrical / Electronics' },
  { id: 'biotech', label: 'Biotechnology / Life Sciences' },
  { id: 'chemical', label: 'Chemistry / Materials' },
  { id: 'medical', label: 'Medical Devices & Healthcare' },
  { id: 'environmental', label: 'Environmental Technology' },
  { id: 'aerospace', label: 'Aerospace & Defense' },
  { id: 'other', label: 'Other / General' },
];

const generateDraft = (form) => {
  const { title, field, problem, features, inventor, filingDate } = form;
  const fieldLabel = FIELDS.find(f => f.id === field)?.label || 'General Technology';
  const featList = features.filter(f => f.trim());

  const claims = featList.map((f, i) =>
    `${i + 1}. A system and method ${i === 0 ? 'comprising' : 'according to Claim 1, further comprising'}:\n   ${f.trim()}.`
  ).join('\n\n');

  const claimsCount = featList.length;

  return `PROVISIONAL PATENT APPLICATION
(Non-Binding Draft — Generated by IPR Awareness Portal)

APPLICATION DATE: ${filingDate || new Date().toISOString().split('T')[0]}
INVENTOR(S): ${inventor}
TECHNICAL FIELD: ${fieldLabel}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TITLE OF INVENTION

"${title}"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ABSTRACT

The present invention discloses "${title}", a novel invention in the field of ${fieldLabel}. The invention addresses the problem of ${problem}. The invention provides an improved solution through ${claimsCount > 0 ? featList[0].toLowerCase() : 'a novel technical approach'}, among other key technical features. The invention is intended for use in the ${fieldLabel} domain and provides significant technical advantages over existing solutions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FIELD OF THE INVENTION

The present invention generally relates to the field of ${fieldLabel}. More specifically, it relates to a system and method for "${title}" that provides improved performance, functionality, and technical capability over prior art solutions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BACKGROUND OF THE INVENTION

Existing solutions in the field of ${fieldLabel} fail to adequately address the problem of ${problem}. Current technologies suffer from limitations including, but not limited to: inefficiency, lack of scalability, inadequate performance, and the inability to handle the specific technical challenges outlined herein. There exists a clear need in the art for an improved system and method that overcomes these limitations.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUMMARY OF THE INVENTION

According to one aspect of the present invention, there is provided a system and method for "${title}" that overcomes the existing problems by providing:

${featList.map((f, i) => `(${i + 1}) ${f.trim()}`).join('\n')}

The invention offers a novel and non-obvious approach to the stated problem that confers substantial technical advantages and utility.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BRIEF DESCRIPTION

Embodiments of the present invention will be better understood when read in conjunction with technical drawings and diagrams. Inventors are advised to prepare the following documents to accompany a formal filing:
  - FIG. 1: System architecture and component diagram
  - FIG. 2: Method flowchart illustrating key process steps
  - FIG. 3: Representative use-case or test-result diagram

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DETAILED DESCRIPTION OF PREFERRED EMBODIMENTS

The following is a detailed description of the preferred embodiment of the present invention. The invention "${title}" is implemented as follows:

${featList.map((f, i) => `[${i + 1}] ${f.trim()}\n    This feature enables [describe technical mechanism here] by leveraging [describe technical means here], resulting in measurable improvements in efficiency, accuracy, or capability.`).join('\n\n')}

Those skilled in the art will recognize that modifications and variations can be made to the preferred embodiments without departing from the spirit and scope of the invention.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

CLAIMS

What is claimed is:

${claims}

${claimsCount + 1}. The system of Claim 1, wherein the invention is implemented in the field of ${fieldLabel} and addresses the problem of: ${problem}.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INVENTOR DECLARATION

I/We hereby declare that:
(a) I/We am/are the original inventor(s) of the subject matter claimed in this application.
(b) I/We have reviewed and understand the contents of this application.
(c) The information disclosed is complete and accurate to the best of my/our knowledge.

Inventor: ${inventor}
Date: ${filingDate || new Date().toISOString().split('T')[0]}
Signature: _______________________________

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

DISCLAIMER: This is a non-binding provisional draft for educational and documentation purposes only. It does NOT constitute a legal patent filing. Please consult a registered patent attorney before submitting to any IP office.

Generated by IPR Awareness Portal | ${new Date().toUTCString()}`;
};

const PatentDraft = () => {
  const [form, setForm] = useState({
    title: '', field: '', problem: '', inventor: '', filingDate: '',
    features: ['', '', ''],
  });
  const [draft, setDraft] = useState('');
  const [copied, setCopied] = useState(false);

  const handleChange = (e) => setForm(f => ({ ...f, [e.target.name]: e.target.value }));
  const handleFeature = (i, val) => setForm(f => {
    const features = [...f.features];
    features[i] = val;
    return { ...f, features };
  });
  const addFeature = () => setForm(f => ({ ...f, features: [...f.features, ''] }));
  const removeFeature = (i) => setForm(f => ({ ...f, features: f.features.filter((_, idx) => idx !== i) }));

  const isValid = form.title && form.field && form.problem && form.inventor && form.features.some(f => f.trim());

  const handleGenerate = () => {
    if (!isValid) return;
    setDraft(generateDraft(form));
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(draft);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 animate-fade-in">
      {/* Header */}
      <div className="text-center mb-10">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-500 to-secondary-500 flex items-center justify-center mx-auto mb-4 shadow-[0_0_30px_rgba(255,183,0,0.3)]">
          <DocumentTextIcon className="h-9 w-9 text-white" />
        </div>
        <h1 className="page-title">Patent Draft Assistant</h1>
        <p className="text-slate-400 max-w-xl mx-auto">
          Fill in your invention details and generate a structured patent draft with Abstract, Claims, Background, and more — ready to refine with an attorney.
        </p>
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Form */}
        <div className="glass-card p-6 space-y-5">
          <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider border-b border-white/5 pb-3">Invention Details</h2>

          <div>
            <label className="label">Invention Title *</label>
            <input name="title" value={form.title} onChange={handleChange} className="input" placeholder="e.g. Adaptive Neural Mesh Compression System" />
          </div>

          <div>
            <label className="label">Technical Field *</label>
            <select name="field" value={form.field} onChange={handleChange} className="input">
              <option value="">Select a field…</option>
              {FIELDS.map(f => <option key={f.id} value={f.id}>{f.label}</option>)}
            </select>
          </div>

          <div>
            <label className="label">Inventor Name(s) *</label>
            <input name="inventor" value={form.inventor} onChange={handleChange} className="input" placeholder="e.g. Jane Smith, John Doe" />
          </div>

          <div>
            <label className="label">Target Filing Date</label>
            <input name="filingDate" type="date" value={form.filingDate} onChange={handleChange} className="input" />
          </div>

          <div>
            <label className="label">Problem Being Solved *</label>
            <textarea name="problem" value={form.problem} onChange={handleChange}
              className="input min-h-[80px] resize-none"
              placeholder="Describe the technical problem or gap this invention addresses…" />
          </div>

          <div>
            <div className="flex items-center justify-between mb-3">
              <label className="label mb-0">Key Technical Features / Claims *</label>
              <button onClick={addFeature} className="flex items-center gap-1 text-xs text-primary-400 hover:text-primary-300 transition-colors">
                <PlusIcon className="h-3.5 w-3.5" /> Add
              </button>
            </div>
            <div className="space-y-2">
              {form.features.map((feat, i) => (
                <div key={i} className="flex gap-2 items-center">
                  <span className="text-xs text-slate-600 font-mono w-5 text-right flex-shrink-0">{i + 1}.</span>
                  <input
                    value={feat}
                    onChange={e => handleFeature(i, e.target.value)}
                    className="input text-sm flex-1"
                    placeholder={`Feature ${i + 1} — e.g. a novel encoding mechanism using…`}
                  />
                  {form.features.length > 1 && (
                    <button onClick={() => removeFeature(i)} className="text-slate-600 hover:text-red-400 transition-colors flex-shrink-0">
                      <TrashIcon className="h-4 w-4" />
                    </button>
                  )}
                </div>
              ))}
            </div>
          </div>

          <button onClick={handleGenerate} disabled={!isValid} className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50">
            <DocumentTextIcon className="h-5 w-5" />
            Generate Patent Draft
          </button>
        </div>

        {/* Output */}
        <div>
          {draft ? (
            <div className="space-y-4">
              <div className="glass-card border border-primary-500/20 p-4 relative">
                <div className="absolute top-0 left-0 right-0 h-0.5 bg-gradient-to-r from-primary-500 to-secondary-500 rounded-t-2xl" />
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-semibold text-primary-300 flex items-center gap-2">
                    <DocumentTextIcon className="h-4 w-4" />
                    Patent Draft — {form.title}
                  </h3>
                  <span className="text-xs text-slate-600 font-mono">PROVISIONAL • DRAFT</span>
                </div>
                <pre className="text-xs text-slate-300 whitespace-pre-wrap font-mono leading-relaxed max-h-[580px] overflow-y-auto bg-black/30 rounded-lg p-4 border border-white/5">
                  {draft}
                </pre>
              </div>
              <div className="flex gap-3">
                <button onClick={handleCopy} className="btn-secondary flex-1 flex items-center justify-center gap-2 text-sm">
                  <ClipboardDocumentCheckIcon className="h-4 w-4" />
                  {copied ? '✅ Copied!' : 'Copy Text'}
                </button>
                <button onClick={() => window.print()} className="btn-primary flex-1 flex items-center justify-center gap-2 text-sm">
                  <PrinterIcon className="h-4 w-4" />
                  Print / Save PDF
                </button>
              </div>
            </div>
          ) : (
            <div className="glass-card border border-dashed border-white/10 p-10 text-center h-full flex flex-col items-center justify-center gap-4">
              <DocumentTextIcon className="h-12 w-12 text-slate-700" />
              <p className="text-slate-500 text-sm">Your formatted patent draft will appear here after you fill in the details and click Generate.</p>
              <div className="text-xs text-slate-600 space-y-1">
                <p>✦ Abstract & Background</p>
                <p>✦ Numbered Claims</p>
                <p>✦ Inventor Declaration</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default PatentDraft;
