import { useState } from 'react';
import { ShieldCheckIcon, ClipboardDocumentCheckIcon, ArrowDownTrayIcon } from '@heroicons/react/24/outline';

const hashText = async (text) => {
  const msgBuffer = new TextEncoder().encode(text);
  const hashBuffer = await window.crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
  return hashHex;
};

const formatHash = (hex) => {
  return hex.match(/.{1,4}/g).join(':').toUpperCase();
};

const VaultCertificate = () => {
  const [form, setForm] = useState({ title: '', description: '', team: '', inventor: '' });
  const [cert, setCert] = useState(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleChange = (e) => setForm(f => ({ ...f, [e.target.name]: e.target.value }));

  const handleGenerate = async () => {
    if (!form.title.trim() || !form.description.trim() || !form.inventor.trim()) return;
    setLoading(true);
    const timestamp = new Date().toISOString();
    const payload = `${form.title}||${form.description}||${form.inventor}||${form.team}||${timestamp}`;
    const hash = await hashText(payload);
    setCert({ ...form, hash, timestamp, certId: hash.substring(0, 12).toUpperCase() });
    setLoading(false);
  };

  const handleCopy = () => {
    if (!cert) return;
    const text = `INNOVATION VAULT — CERTIFICATE OF ORIGINALITY\n\nCertificate ID: ${cert.certId}\nProject Title: ${cert.title}\nInventor(s): ${cert.inventor}${cert.team ? `\nTeam: ${cert.team}` : ''}\nTimestamp (UTC): ${cert.timestamp}\n\nSHA-256 Fingerprint:\n${formatHash(cert.hash)}\n\nDescription:\n${cert.description}\n\nThis certificate confirms the cryptographic existence of the above project at the stated timestamp. Generated by IPR Awareness Portal.`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => window.print();

  return (
    <div className="max-w-4xl mx-auto px-4 py-8 animate-fade-in">
      {/* Header */}
      <div className="text-center mb-10">
        <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-primary-500 to-secondary-500 flex items-center justify-center mx-auto mb-4 shadow-[0_0_30px_rgba(255,183,0,0.3)]">
          <ShieldCheckIcon className="h-9 w-9 text-white" />
        </div>
        <h1 className="page-title">Vault Certificate of Originality</h1>
        <p className="text-slate-400 max-w-xl mx-auto">
          Generate a cryptographic proof-of-existence for your project using SHA-256. The hash anchors your idea to a specific point in time.
        </p>
        <div className="inline-flex items-center gap-2 mt-3 px-3 py-1 bg-primary-500/10 border border-primary-500/20 rounded-full text-primary-300 text-xs font-mono">
          🔐 Uses real SHA-256 via Web Crypto API
        </div>
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        {/* Form */}
        <div className="glass-card p-6 space-y-5">
          <h2 className="text-sm font-semibold text-slate-400 uppercase tracking-wider border-b border-white/5 pb-3">Project Details</h2>

          <div>
            <label className="label">Project / Invention Title *</label>
            <input name="title" value={form.title} onChange={handleChange}
              className="input" placeholder="e.g. AeroFold Drone Mechanism" />
          </div>

          <div>
            <label className="label">Primary Inventor / Author *</label>
            <input name="inventor" value={form.inventor} onChange={handleChange}
              className="input" placeholder="Your full name" />
          </div>

          <div>
            <label className="label">Team / Organization (optional)</label>
            <input name="team" value={form.team} onChange={handleChange}
              className="input" placeholder="e.g. IIIT Hyderabad — Lab B" />
          </div>

          <div>
            <label className="label">Technical Description *</label>
            <textarea name="description" value={form.description} onChange={handleChange}
              className="input min-h-[120px] resize-none" placeholder="Describe your invention in detail. More specific = more unique hash." />
          </div>

          <button
            onClick={handleGenerate}
            disabled={loading || !form.title || !form.description || !form.inventor}
            className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50"
          >
            <ShieldCheckIcon className="h-5 w-5" />
            {loading ? 'Computing SHA-256 Hash…' : 'Generate Certificate'}
          </button>
        </div>

        {/* Certificate Preview */}
        <div>
          {cert ? (
            <div className="relative">
              {/* Certificate */}
              <div id="vault-certificate" className="glass-card border border-primary-500/30 p-8 relative overflow-hidden shadow-[0_0_40px_rgba(255,183,0,0.15)]">
                {/* Background decoration */}
                <div className="absolute inset-0 opacity-[0.03]" style={{
                  backgroundImage: 'repeating-linear-gradient(45deg, #ffb700 0, #ffb700 1px, transparent 0, transparent 50%)',
                  backgroundSize: '10px 10px'
                }} />
                <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-primary-500 via-secondary-500 to-primary-500" />

                <div className="relative z-10">
                  <div className="text-center mb-6">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-primary-500 to-secondary-500 flex items-center justify-center mx-auto mb-3">
                      <ShieldCheckIcon className="h-7 w-7 text-white" />
                    </div>
                    <p className="font-mono text-[10px] text-primary-500/60 uppercase tracking-[0.4em] mb-1">Innovation Vault</p>
                    <h2 className="text-lg font-bold text-white">Certificate of Originality</h2>
                    <p className="font-mono text-[10px] text-slate-500 mt-1">CERT-ID: {cert.certId}</p>
                  </div>

                  <div className="border border-white/5 rounded-lg p-4 mb-4 space-y-2">
                    <div className="flex justify-between text-xs">
                      <span className="text-slate-500">Project</span>
                      <span className="text-white font-semibold text-right max-w-[60%] truncate">{cert.title}</span>
                    </div>
                    <div className="flex justify-between text-xs">
                      <span className="text-slate-500">Inventor</span>
                      <span className="text-white font-semibold">{cert.inventor}</span>
                    </div>
                    {cert.team && (
                      <div className="flex justify-between text-xs">
                        <span className="text-slate-500">Team</span>
                        <span className="text-white font-semibold">{cert.team}</span>
                      </div>
                    )}
                    <div className="flex justify-between text-xs">
                      <span className="text-slate-500">Sealed (UTC)</span>
                      <span className="text-primary-300 font-mono text-[10px]">{new Date(cert.timestamp).toUTCString()}</span>
                    </div>
                  </div>

                  <div className="bg-black/40 border border-primary-500/20 rounded-lg p-4 mb-5">
                    <p className="text-[10px] text-primary-500/60 font-mono uppercase tracking-widest mb-2">SHA-256 Fingerprint</p>
                    <p className="font-mono text-[11px] text-primary-300 break-all leading-relaxed">
                      {formatHash(cert.hash)}
                    </p>
                  </div>

                  <p className="text-[10px] text-slate-600 text-center leading-relaxed">
                    This certificate confirms the cryptographic existence of the above project at the stated UTC timestamp. This document does not constitute legal patent filing.
                  </p>
                </div>
              </div>

              {/* Actions */}
              <div className="flex gap-3 mt-4">
                <button onClick={handleCopy} className="btn-secondary flex-1 flex items-center justify-center gap-2 text-sm">
                  <ClipboardDocumentCheckIcon className="h-4 w-4" />
                  {copied ? 'Copied!' : 'Copy Text'}
                </button>
                <button onClick={handlePrint} className="btn-primary flex-1 flex items-center justify-center gap-2 text-sm">
                  <ArrowDownTrayIcon className="h-4 w-4" />
                  Print / Save
                </button>
              </div>
            </div>
          ) : (
            <div className="glass-card border border-dashed border-white/10 p-10 text-center h-full flex flex-col items-center justify-center gap-4">
              <ShieldCheckIcon className="h-12 w-12 text-slate-700" />
              <p className="text-slate-500 text-sm">Fill in your project details and click Generate to create your cryptographic certificate.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default VaultCertificate;
